receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: telemetry
    timeout: 5s
    username: otel
    password: ${env:CLICKHOUSE_PASSWORD}
  logging:
    loglevel: debug
service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [clickhouse, logging]
    metrics:
      receivers: [otlp]
      exporters: [clickhouse, logging]
    logs:
      receivers: [otlp]
      exporters: [clickhouse, logging]
